name: Kind
on: [pull_request, push]
jobs:
  build:
    name: Kind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Kind
        uses: engineerd/setup-kind@v0.3.0
        with:
          version: "v0.7.0"
      - name: Testing
        run: |
          make build TAG=latest
          kind load docker-image quay.io/dulltz/megaconfigmap:latest
